### ISSUE TITLE
Link to the Broadlink integration translation team in lokalise

### ISSUE THREAD

**Issue by alicialiali** [felipediel/broadlink-hacktools#2]
Hi Felipe, how are you?
In the PR I opened with the translation that I had done a few days ago on the Home Assistant github you informed me that the translations were done using the lokalise site but you didn't leave a link to join the translation team. I couldn't find this link on Broadlink's github or elsewhere.
I couldn't find any e-mail or way to contact you to get this link, could you give me the link?
I would love to contribute because most Brazilians do not understand English and having the integration in Brazilian Portuguese would be of great help.
Thanks.

**Comment by felipediel** [comment]
Opa Leandro, tudo certo?
O processo de tradução é um pouco mais complicado que um pull request, você precisa se cadastrar no time de tradutores para poder enviar modificações. Neste [link](https://developers.home-assistant.io/docs/translations/) você pode encontrar mais informações, incluindo os links para se juntar às equipes de tradução. Valeu, um abraço!

**Comment by alicialiali** [comment]
> Opa Leandro, tudo certo? O processo de tradução é um pouco mais complicado que um simples pull request, você precisa se cadastrar no time de tradutores para poder enviar modificações. Neste [link](https://developers.home-assistant.io/docs/translations/) você pode encontrar mais informações, incluindo os links para se juntar às equipes de tradução. Valeu, um abraço!

Oi Felipe, obrigado pelo retorno. Tudo certo e contigo?
Sei sobre o Lokalise, já faço parte da equipe de tradução do Home Assistant e já traduzimos o Home Assistant todo, tanto o core quanto o frontend. Ele já está com 100%! Inclusive traduzi sozinho o app de IOS e uns 85% do app de Android do Home Assistant. Não encontrei lá para tradução da integração do Broadlink por isso vim te perguntar se é algum projeto separado no Lokalise. O HACS é um projeto separado (traduzi 50% dele e já ta 100% também) também no Lokalise e outros componentes e add-on também são.
Se a tradução da integração do Broadlink for junto com o projeto do Home Assistant gostaria de pedir pra verificar se realmente está junto. Gostaria muito de adicionar a tradução em português, acredito que é uma das integrações mais usadas.
Um abraço!

**Comment by felipediel** [comment]
Ah beleza! A integração Broadlink faz parte do core do Home Assistant, você provavelmente encontrará ela lá, embora eu não tenha acesso ao grupo no Lokalise pra te confirmar.

**Comment by alicialiali** [comment]
> Ah beleza! A integração Broadlink faz parte do core do Home Assistant, você provavelmente encontrará ela lá, embora eu não tenha acesso ao grupo no Lokalise pra te confirmar.

Procurei melhor lá na tradução do core do Home Assistant e achei a tradução do Broadlink mas tinham erros, arrumei os erros e espero que nas próximas atualizações apliquem!

**Comment by felipediel** [comment]
Maravilha. Obrigado!
